### ISSUE TITLE
Can't open http://localhost:3000

### ISSUE THREAD

**Issue by langolf** [zeit/hyperterm#98] opened 2016-07-15 19:44 UTC
It seems we cannot open url without domain zone. But I really need :)

Also hyperterm crashes when I try add `.com` in the end
`http://localhost:3000.com`

**Comment by kinduff** [comment] 2016-07-15 20:09
👍 Able to reproduce. Unable to open localhost y crashes with dot com at the end.

**Comment by kinduff** [comment] 2016-07-15 20:12
This is a duplicate of #97, the `.com` at the end should be also fixed, not sure if that bug is part of the same issue.

**Comment by iamstarkov** [comment] 2016-07-21 10:33
just ran `open http://localhost:3000` and that works perfectly fine

**Comment by langolf** [comment] 2016-07-21 10:41
@iamstarkov We are talking about opening inside hyperterm as normal urls. Hyperterm already can do this with normal urls.

**Comment by iamstarkov** [comment] 2016-07-21 11:50
@langolf what do you mean?

**Comment by langolf** [comment] 2016-07-21 11:55
@iamstarkov you can open any url inside hyperterm window like a browser
https://monosnap.com/file/jzAKLD1oI3wPAi5U3Go7r17HivvOTk

**Comment by iamstarkov** [comment] 2016-07-21 12:10
how did you do this?

**Comment by langolf** [comment] 2016-07-21 12:12
@iamstarkov just type `http://someurl` or `www.someurl` in shell

**Comment by iamstarkov** [comment] 2016-07-21 12:16
thats neat, how do use it?

**Comment by langolf** [comment] 2016-07-21 12:23
I use vim for development. So it's very convenient to have "browser" in next-tab. E.g. I don't need to cmd-tab to browser to check markup.

**Closed** 2016-07-28 20:18 UTC

**Comment by kopollo** [comment] 2017-11-02 13:58
try from here [http://localhost.support/:3000](http://localhost.support/:3000)
