### ISSUE TITLE
Alt modifiers don't do anything on an AZERTY keyboard

### ISSUE THREAD

**Issue by Haroenv** [zeit/hyperterm#195] opened 2016-07-17 08:55 UTC
For example typing `~` is <kbd>alt</kbd><kbd>n</kbd>, but this displays the letter as if no modifier had been pressed. For numbers it doesn't show the correct modified character as well. Some letters show the letter as if it'd been pressed with <kbd>shift</kbd>, others as if it was typed without any modifier.

AZERTY keyboard as a reference: 

![image of an AZERTY keyboard](http://img.staticmacg.com/2012/10/macgpic_1349359724_scaled_optim.jpg)

This was tested with `v0.5.0` on OS X 10.11.5 with keyboard set to French (Numerical)

**Comment by jaimeeee** [comment] 2016-07-17 18:09
This is a duplicate of #29

**Comment by Haroenv** [comment] 2016-07-17 18:13
Not completely I think. Yours was entering the unicode  codepoints, but my issue is that it doesn't update at all, whether option is pressed or not, am I correct @jaimeeee

**Comment by jaimeeee** [comment] 2016-07-17 18:14
@Haroenv both, I can't work with Alt either

**Comment by Haroenv** [comment] 2016-07-17 18:16
Aha, so your issue is more broad

**Comment by chabou** [comment] 2016-07-18 11:20
I think it is related to hterm : https://github.com/macton/hterm#how-do-i-enter-accented-characters
 `term_.prefs_.set('alt-sends-what', 'browser-key')` is set there : https://github.com/zeit/hyperterm/blob/master/app/lib/components/term.js#L38
But hterm documentation says : 

> Note that composed characters (those that require multiple keystrokes) are not currently supported by this mode.

**Comment by chabou** [comment] 2016-07-18 12:19
Chromium's hterm is used (with hterm-umdjs) but this is probably the same issue : https://github.com/chromium/hterm/blob/master/js/hterm_keyboard.js#L389

**Comment by CodeTheory** [comment] 2016-07-26 21:48
I agree with @jaimeeee. This is a duplicate.

**Closed by CodeTheory** 2016-07-26 21:48 UTC
