### ISSUE TITLE
Tabbing issue

### ISSUE THREAD

**Issue by anushkamahesh** [zeit/hyperterm#256] opened 2016-07-18 19:15 UTC
if you type something **(cd, git,..)** and then press _tab_ button in keyboard, it will popup something related to the command you type in but if you try to delete the content you typed**, it won't delete**. it will be there. you can type other thing but as you wish it will work but the text you typed would be there until you do something with terminal view.

Regards, 
_A.M_

**Comment by CodeTheory** [comment] 2016-07-18 19:26
This is a duplicate of #183.

**Closed** 2016-07-26 21:43 UTC
Labels: Is Duplicate
