### ISSUE TITLE
Cannot type ˜, single quote ' or double quotes " on US international keyboard

### ISSUE THREAD

**Issue by steren** [zeit/hyperterm#230] opened 2016-07-18 09:03 UTC
My keyboard layout is US international.
When I type the key with the character ', nothing happens in the terminal.
Same if I press shift and press the same key (in order to produce ")

This is a big blocker for me ' 

Pressing space after pressing this key has no effect. It definitely should print a '

**Comment by weslleyaraujo** [comment] 2016-07-18 09:57
++ same as `~` for example.

**Comment by asantos00** [comment] 2016-07-18 10:20
Same here with ~. For me it is kind of a critical bug cause of the ~ used for home directory.

Good job with the project!

**Comment by lfuelling** [comment] 2016-07-18 12:10
The tilde doesn't work on german keyboard layout either. Also the umlauts (ö, ä, ü, ¨) aren't working (displaying as unicode symbols).

**Comment by petetnt** [comment] 2016-07-18 13:12
(Semi) duplicate of #213

**Comment by diogobeda** [comment] 2016-07-18 14:26
Being solved at #214

**Closed** 2016-07-26 18:14 UTC
