### ISSUE TITLE
Font Clipping

### ISSUE THREAD

**Issue by fingermark** [zeit/hyperterm#728] opened 2016-09-20 17:12 UTC
Any ideas on how to fix this font clipping issue?  It seems to clip on the g's and p's.  I'm trying out "Inconsolata-dz for Powerline dz".

![font](https://cloud.githubusercontent.com/assets/984414/18680917/9a3aebc2-7f33-11e6-9665-358b88e4016c.png)

**Comment by davegomez** [comment] 2016-09-22 20:55
That seems to be a line-height problem, have you tried to reproduce it with another font?

**Comment by CodeTheory** [comment] 2016-09-25 17:29
Duplicate of #628.

**Closed by CodeTheory** 2016-09-25 17:29 UTC
