### ISSUE TITLE
Change Default Login Shell

### ISSUE THREAD

**Issue by kurisubrooks** [zeit/hyperterm#491] opened 2016-07-28 23:53 UTC
Currently there's no way to change the login shell, that i'm aware of, so i'm currently stuck in zsh, but i'd like to be using bash.

**Comment by CodeTheory** [comment] 2016-07-29 00:02
Duplicate of #81.

**Closed by CodeTheory** 2016-07-29 00:02 UTC

**Comment by sourleangchhean168** [comment] 2017-07-29 15:19
You can check this out: https://youtu.be/fs7yWlB2dSU
