### ISSUE TITLE
Uncaught Exception when creating new directory with finder

### ISSUE THREAD

**Issue by Jonas-Drotleff** [zeit/hyperterm#705] opened 2016-09-10 22:23 UTC
When you have hyperterm open and create a new directory, the following exception is thrown.
```
Uncaught Exception:
Error: watch /Users/jonasdrotleff/Workspace/dev ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

This does only occur when creating directories, not files.

Also, it does not matter whether the newly created directory is (in) a subdirectory or not. So if you are in `~/Test/` and create a new directory `~/Test/newdir/` it behaves exactly the same as if you would have created a directory in the parent dir: `~/newdir/` 

Version 0.7.1 (0.7.1.36)

**Comment by matheuss** [comment] 2016-09-10 22:52
Kinda duplicate of #225 😰

**Closed by matheuss** 2016-09-10 22:52 UTC
