### ISSUE TITLE
A few characters don't work with a US international keyboard

### ISSUE THREAD

**Issue by tleunen** [zeit/hyperterm#624] opened 2016-08-15 19:33 UTC
I have a keyboard set in US International and a few characters don't work.

~, ` and " are a few examples.

With a US keyboard, everything works fine.

**Comment by CodeTheory** [comment] 2016-08-15 19:44
I appreciate the report! But please in future use the search feature to find a duplicate of your issues. #518 (and others)

**Closed by CodeTheory** 2016-08-15 19:44 UTC

**Comment by tleunen** [comment] 2016-08-15 20:17
My bad, sorry :/
