### ISSUE TITLE
Possible to switch windows with ⌘-[0-9]?

### ISSUE THREAD

**Issue by hairyhenderson** [zeit/hyperterm#558] opened 2016-08-04 12:12 UTC
I've mostly used Terminal.app for the past few years, and I tend to have a number of different windows open (not tabs), and arrange them in grids (with keyboard shortcuts, using [Spectacle](https://www.spectacleapp.com)). What makes this work really well is that the first 9 Terminal windows can be switched between with ⌘-n (where n is the window's index).

Would it be possible for HyperTerm to adopt this behaviour as well?

**Comment by hhsnopek** [comment] 2016-08-04 14:07
The current behavior of `cmd-n` is to switch tabs, as does chrome and many other applications on OSX - I don't think HyperTerm well end up adopting this behavior, they could make it customizable so you could control the windows index...

**Comment by bevacqua** [comment] 2016-08-04 17:12
FYI `hyperterm-tab-numbers` does this.

**Comment by hairyhenderson** [comment] 2016-08-04 17:50
@hhsnopek - thanks for pointing that out - I _totally_ didn't notice that... I don't generally use tabs in my terminal, and I've gotten used to using `⌘-⇧-[`/`⌘-⇧-]` to switch between tabs.

Sounds like a plugin is definitely in order here. I'm _brand new_ to HyperTerm (so's the rest of the Internet, I guess), so I haven't really figured out plugins yet :wink:

@bevacqua - cool, thanks for the tip

**Comment by albinekb** [comment] 2016-08-05 23:53
Duplicate of #203 🙌

**Closed by albinekb** 2016-08-05 23:53 UTC
Labels: Is Duplicate

**Comment by hairyhenderson** [comment] 2016-08-06 01:20
Thanks @albinekb - didn't find that one when I searched :grin:
