### ISSUE TITLE
ñ Letter dont work

### ISSUE THREAD

**Issue by lmichailian** [zeit/hyperterm#457] opened 2016-07-27 13:10 UTC
On spanish mac (OS X 10.11.6  ) keyboard letter ñ shows <00c3><00b1>

**Comment by CodeTheory** [comment] 2016-07-27 14:43
Duplicate of #29.

**Closed by CodeTheory** 2016-07-27 14:43 UTC

**Comment by lmichailian** [comment] 2016-08-01 10:41
My Apologies 💃

**Comment by dannegm** [comment] 2017-12-17 10:48
But, how does repair this?

**Comment by albinekb** [comment] 2017-12-18 17:35
Try using hyper canary, where we have replaced the terminal rendering lib: https://zeit.co/blog/canary/hyper
