### ISSUE TITLE
Newlines appear when text is copied.

### ISSUE THREAD

**Issue by EtherTyper** [zeit/hyperterm#243] opened 2016-07-18 16:06 UTC
Text and entered commands wrap around when you reach the end of the terminal emulator's length. However, due to the Chromium implementation of said wrap-around, It treats the end of the terminal simulator as a newline.

**Comment by CodeTheory** [comment] 2016-07-26 22:16
I believe this was mentioned in other issues and also fixed with the introduction of the `LANG` env variable. Please reopen if the issue isn't resolved.

**Closed by CodeTheory** 2016-07-26 22:16 UTC
