### ISSUE TITLE
Can't use alt+n for ~

### ISSUE THREAD

**Issue by lukaskollmer** [zeit/hyperterm#372] opened 2016-07-23 07:55 UTC
I'm using a German keyboard. In all other apps, I can use `alt+n` to insert `~`. (This works in the default Terminal and iTerm2 as well).

However, in hyperterm, `alt+n` does nothing. Is there a way I can fix this or does this need to be implemented in hyperterm itself?

**Comment by matheuss** [comment] 2016-07-23 12:18
Duplicate of #66

**Closed** 2016-07-26 18:22 UTC
Labels: duplicate
