### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by laodalaoda520** [zeit/hyperterm#754] opened 2016-09-28 10:31 UTC
Uncaught Exception:
TypeError: Cannot read property 'write' of undefined
    at Server.rpc.on (/Applications/HyperTerm.app/Contents/Resources/app/index.js:162:24)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.ipcListener (/Applications/HyperTerm.app/Contents/Resources/app/rpc.js:32:11)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

**Comment by laodalaoda520** [comment] 2016-09-28 10:32
it happend when i exit a tab with sort key "command + D"

**Comment by flybayer** [comment] 2016-09-28 14:17
It looks like this is a duplicate of #225 :)

**Comment by CodeTheory** [comment] 2016-10-04 21:07
I believe this is a duplicate also.

**Closed by CodeTheory** 2016-10-04 21:07 UTC
