### ISSUE TITLE
Can't use ~ to cd to home with Spanish keyboard.

### ISSUE THREAD

**Issue by luisherranz** [zeit/hyperterm#627] opened 2016-08-17 10:33 UTC
Loving `hyperterm` so far ☺️  

I can't use the ~ symbol with a Spanish keyboard. Here it should be `alt+ñ` which is located in the english `: ;` key.

![mac-spanish-keyboard_1024x1024](https://cloud.githubusercontent.com/assets/3305402/17733347/6992c71a-6476-11e6-87e9-86fa1ec335f1.png)

It works fine on Atom so I guess Electron is not the issue.

Is there a way I can see what's going on with Redux Devs or a breakpoint somewhere? I'd love to help. 

> *BTW, for other people with this issue, you can use* `$HOME` *as a workaround*.

**Comment by CodeTheory** [comment] 2016-08-19 22:42
This is a duplicate of #29.

**Closed by CodeTheory** 2016-08-19 22:42 UTC

**Comment by luisherranz** [comment] 2016-08-19 22:45
Ok, thanks
