### ISSUE TITLE
Can’t open preferences 

### ISSUE THREAD

**Issue by bensk** [zeit/hyperterm#344] opened 2016-07-21 19:22 UTC
I get this every time I try to open preferences:
```
➜ ~ # Attempting to open ~/.hyperterm.js with your $EDITOR

or! # If this doesn't work, open it manually with your favorite edit 

➜ ~ $EDITOR ~/.hyperterm.js && exit
bash: /Users/Ben/.hyperterm.js: Permission denied

➜ ~ 
```

        -

        HyperTerm 0.5.0
        Electron 1.2.5
        darwin x64 15.6.0

**Comment by rauchg** [comment] 2016-07-21 19:45
We have some fixes coming for preferences. Keep us posted when we release `0.6.0`

**Comment by bensk** [comment] 2016-07-21 19:49
Thanks!
👍

**Comment by NKjoep** [comment] 2016-07-25 09:54
just installed the 0.6.0 and got the same problem :) 

I had to create manually the `~/.hyperterm.js` and then open it manually. It keeps saying: 

```shell
~ ∫ # Attempting to open ~/.hyperterm.js with your $EDITOR
~ ∫ # If this doesn't work, open it manually with your favorite editor!
~ ∫ $EDITOR ~/.hyperterm.js && exit
/Users/me/.hyperterm.js: line 1: module.exports: command not found
/Users/me/.hyperterm.js: line 2: config:: command not found
/Users/me/.hyperterm.js: line 3: //: is a directory
/Users/me/.hyperterm.js: line 4: fontSize:: command not found
/Users/me/.hyperterm.js: line 6: //: is a directory
/Users/me/.hyperterm.js: line 7: fontFamily:: command not found
/Users/me/.hyperterm.js: line 9: syntax error near unexpected token `('
/Users/me/.hyperterm.js: line 9: `    // terminal cursor background color (hex)'
~ ∫ 
```

**Comment by moloafrica** [comment] 2016-07-26 13:07
same case here 
![screen shot 2016-07-26 at 16 06 22](https://cloud.githubusercontent.com/assets/1729842/17138877/f420ef66-534a-11e6-9152-d6ed6c2b8f1f.png)

**Comment by dak0rn** [comment] 2016-07-26 13:28
The problem is that the `$EDITOR` variable is unset.
Therefore, `$EDITOR ~/.hyperterm.js` is evaluated as if one tries to execute `~/.hyperterm.js` with the default shell.

(Temporary?) workaround could be to set the very variable in your `.profile`/`.bashrc`/`.zshrc`/whatever, e.g. `EDITOR=vim`.

**Comment by moloafrica** [comment] 2016-07-27 05:59
@dak0rn I am using atom as the text editor.  When I run `$ atom hyperterm.js` it creates a new file which doesn't show the config options such as changing the foreground or background color. How do I change these options?

**Comment by dak0rn** [comment] 2016-07-27 06:01
@moloafrica You have to be careful about the path. The config file is located in your home directory and begins with a dot. `atom ~/.hyperterm.js` should open it correctly.

**Comment by MrRio** [comment] 2016-07-30 15:34
This is fixed in this PR -- https://github.com/zeit/hyperterm/pull/517

**Comment by flybayer** [comment] 2016-09-20 19:46
@matheuss I'm pretty sure this can be closed! :muscle:

**Comment by matheuss** [comment] 2016-09-20 19:47
Thank you @flybayer! 😄

**Closed by matheuss** 2016-09-20 19:47 UTC
Labels: Priority: Medium, Status: Help Wanted, Type: Bug
