### ISSUE TITLE
NPM Error Message not sure what it means

### ISSUE THREAD

**Issue by sandysaders** [zeit/hyperterm#145] opened 2016-07-16 01:27 UTC
I keep getting the error message below and I'm not sure how to fix it. I have `nvm` on my computer and can run npm commands. I tried running npm commands in `hyperterm` and they worked so not sure how to fix this. (not to familiar with terminal things.) 

<img width="322" alt="screen shot 2016-07-15 at 9 23 07 pm" src="https://cloud.githubusercontent.com/assets/19610736/16891974/5d5edf50-4ad2-11e6-9e9a-6cbae640860a.png">

**Comment by montogeek** [comment] 2016-07-16 02:33
Duplicate of #106 and #89

**Closed** 2016-07-17 15:45 UTC
