### ISSUE TITLE
Can Type ~

### ISSUE THREAD

**Issue by MatthD** [zeit/hyperterm#539] opened 2016-08-01 11:41 UTC
Hello !

First thanks to all this job :) 
I am not able to insert ~caracter on hyperterm (OSX french keyboard)
I have read all opened & closed issues but did not find any solution. Is There a bypass while your are on it ? :)

**Comment by MrRio** [comment] 2016-08-01 11:43
Try this? https://github.com/zeit/hyperterm/pull/521

**Comment by MatthD** [comment] 2016-08-01 12:06
Done swtiching to us keyboard ! but not working too 😢

**Comment by CodeTheory** [comment] 2016-08-01 12:15
Duplicate of #466. A fix is in progress. 😄

**Closed by CodeTheory** 2016-08-01 12:15 UTC
