### ISSUE TITLE
Send escape for option (MacOS/OSX)

### ISSUE THREAD

**Issue by curioussavage** [zeit/hyperterm#330] opened 2016-07-21 00:36 UTC
Iterm 2 lets you configure option to send the code for escape. It would be awesome to have some way to configure hyperterm to do this as well. Us poor mac users want meta keys too!

**Comment by domachine** [comment] 2016-07-21 06:17
Yap, would be awesome for jumping words e.g. `<option>+<left>`

**Comment by chriskrycho** [comment] 2016-08-16 16:43
This is a *cannot-use-the-app* deficiency for me (and, I suspect, for quite a few others): I use <kbd>option</kbd><kbd>f</kbd> (word forward), <kbd>option</kbd><kbd>b</kbd> (word back), <kbd>option</kbd><kbd>d</kbd> (delete word), etc. a *lot*.

**Comment by azer** [comment] 2016-09-26 10:30
Emacs users also need this feeature.

**Comment by rye** [comment] 2016-10-05 20:33
I do believe that the relevant code could be found in [lib/hterm.js](https://github.com/zeit/hyperterm/blob/71ae9b7e00adad8f58d5a4c715550c888f699df8/lib/hterm.js#L39-L140).  It appears that #686, which added the support for settings related to modifierKeys, may have resolved this issue.  However, I, personally, would still like to see more rich support for the Command and Option keys being used.

**Comment by ekmartin** [comment] 2016-10-05 20:36
You're right @rye, setting `modifierKeys` to `{ altIsMeta: true }` will allow the behavior described here. I'm gonna close this, but feel free to open another issue regarding the rich support.

**Closed by ekmartin** 2016-10-05 20:36 UTC
Labels: Type: Feature Request

**Comment by curioussavage** [comment] 2016-11-15 18:51
Can somebody confirm this works for `option` on osx? Or tell me what else I need to do for this to work?

I set `altIsMeta: true` in the config

using `sed -n l` for option+h I get:  `˙` while in iterm 2 I get `^[h`

**Comment by domachine** [comment] 2016-11-16 08:39
@curioussavage Hey, yeah I can confirm that this works (as far as I expect it) on OSX. If I press `option+h` it tries to show a manual page. And if I press `option+b` the cursor jumps back a word. Just as I would expect it. The start of my `~/.hyper.js` looks like this:

![screen shot 2016-11-16 at 09 35 54](https://cloud.githubusercontent.com/assets/413208/20340151/7f787000-abe0-11e6-9216-640a7ec98d6e.png)

**Comment by curioussavage** [comment] 2016-11-18 23:44
@domachine so I am assuming you actually see the `^[`` if you use sed or another approach to see what the terminal receives? I still get nothing. 

I even tried using karabiner to set option key to send Esc globally which worked: I saw `^[h` in sed but hyperterm does nothin (I have Meta-h set up to switch panes in tmux) option-b does jump backwards though.

**Comment by FelikZ** [comment] 2017-01-05 23:03
On Windows 10, I have:
modifierKeys: {
      altIsMeta: true,
      cmdIsMeta: true
    },

And still alt is ignored.

**Comment by nwshane** [comment] 2017-02-02 06:41
I added `modifierKeys: { altIsMeta: true }` to my `~/.hyper.js` config file a few weeks ago, but it still didn't work. Came back to it today and realized my mistake: I had added `modifierKeys: { altIsMeta: true }` to the `module.exports` object, not the `config` object within `module.exports`. To summarize...

Incorrect:
```
module.exports = {
  config: {},
  modifierKeys: { altIsMeta: true }
}
```

Correct:
```
module.exports = {
  config: {
    modifierKeys: { altIsMeta: true }
  }
}
```

Hope that helps someone.

**Comment by FelikZ** [comment] 2017-02-11 21:36
@nwshane I did it right, but no effect still

**Comment by ppot** [comment] 2017-02-11 23:35
Can you list the desired feature and keybinding to https://github.com/ppot/hyper/issues/11

**Comment by drorata** [comment] 2017-02-16 07:50
I added 

```
modifierKeys: {
      altIsMeta: true
    }
```

to the `config` inside `module.exports` but it still doesn't work. When trying `Alt+b`, `Alt+f` or `Alt+.` I get `∫`, `ƒ` and `≥`, respectively.

**Comment by sorahn** [comment] 2017-02-23 18:02
What is missing is an `altIsEscape` option. 

![altIsEscape](http://i.imgur.com/BWNLFLR.png)

**Comment by antonyr** [comment] 2017-05-08 06:55
@ekmartin What we need is `altIsEscape` option too

**Comment by ppot** [comment] 2017-05-08 16:00
The fix will be in #1509

**Comment by sandric** [comment] 2017-07-15 23:37
I'm not seeing this.. I found new `cmdIsMeta` but I don't see it send any escape codes, rather some 'special characters'. Is there `cmdIs+Esc`?

**Comment by samuela** [comment] 2018-06-05 02:28
I've tried all the options here but none of them seem to offer the same thing as Terminal's "Use Option as Meta key" option. If I do `option+left/right arrow` or `option+backspace` they don't do the same thing as one should expect.

**Comment by deonquentinzoss** [comment] 2022-06-08 16:13
For those still struggling after adding altIsMeta line to the config, make sure to put a comma after the line, if other lines follow it
