### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by JiLiZART** [zeit/hyperterm#162] opened 2016-07-16 10:39 UTC
![](https://3.downloader.disk.yandex.ru/disk/484fde40a22afad8196c2dd7f5a9ef8bfcb08e5f344c0dc08a7cedc7a974f6a1/578a46ad/c0-_RT1cZQr1yY8kyWQlW6rF4foCOtd9M_SWRJN84-pf92JRddRH6MK_RHRSQdJxcnfHp1nYo198WaS07vcyBA%3D%3D?uid=0&filename=2016-07-16_12-36-15.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=28606&hid=755cae4c7a1353dfd48be553771813f8&media_type=image&tknv=v2&etag=8c3326944256ff2400d56e7f4d9ea26d)

OSX 10.11.5

**Comment by eljefedelrodeodeljefe** [comment] 2016-07-16 11:30
Same problem. Holds me from using  cocoapods --> pod install

**Comment by thvd** [comment] 2016-07-16 12:14
Duplicate of #161 I think?

**Closed** 2016-07-16 14:14 UTC
