### ISSUE TITLE
Closing hyperterm doesn't quit processes

### ISSUE THREAD

**Issue by tleunen** [zeit/hyperterm#623] opened 2016-08-15 14:54 UTC
I had hyperterm opened with a process to start a http server with node, but I quit hyperterm and the node process is still alive. So the only way to kill the http server is to find the PID and kill it manually :/

**Comment by MrRio** [comment] 2016-08-15 16:11
Hi @tleunen -- is this against latest master, or 0.7.x?

**Comment by tleunen** [comment] 2016-08-15 16:12
Yes, with Version 0.7.1 (0.7.1.36) (build from brew)

**Comment by MrRio** [comment] 2016-08-15 16:28
Can you try against master using the Contribute instructions in the readme?

**Comment by tleunen** [comment] 2016-08-15 21:19
Same on master. Run something, start a node http server for example and then quit (cmd+q).

**Comment by juanbrujo** [comment] 2016-08-24 12:31
a question: how do I quit a process? I used `command + dot` in Terminap.app

**Comment by juanbrujo** [comment] 2016-08-24 12:34
OK I see it is using `ctrl + c`.

**Comment by matheuss** [comment] 2016-09-01 02:32
I can't reproduce it here 😕 Can you provide more info and perhaps a snippet of the server that you are using? with [`list`](https://github.com/zeit/micro-list) running, if I quit the terminal the server goes away.

**Comment by tleunen** [comment] 2016-09-01 02:51
Steps:
1. Run micro-list: `list`
2. Quit hyperterm with `cmd+q`.

Notice localhost:3000 is still accessible.

But I just noticed it's the same behavior in the mac terminal, except it warns that a process is running before quitting.

**Comment by matheuss** [comment] 2016-09-01 02:59
Which shell are you using?
![cant-reproduce](https://cloud.githubusercontent.com/assets/4721750/18153922/e2c25b44-6fd6-11e6-9955-40ec9a44b13f.gif)
_(WTF is this shadows doing 🤔)_

**Comment by tleunen** [comment] 2016-09-01 03:29
zsh

**Comment by matheuss** [comment] 2016-09-01 03:30
Same here 😰 Let's see if someone else can reproduce 🤔

**Comment by tleunen** [comment] 2016-09-01 03:33
Anyway, it's the same behavior in the mac terminal... I'll try to find if there's a setting in my zsh making it keeping the process alive.

But could we have a prompt before exiting when a process is running? Do you know if there's already a ticket, or should I create a new one?

**Comment by matheuss** [comment] 2016-09-01 03:36
I do not remember seeing any issue about this. Go ahead ☺️

**Comment by matheuss** [comment] 2016-09-01 17:24
Since 1) I can't reproduce 2) You report seeing the same behavior on `Terminal.app`, I'm closing this 😄 Feel free to reopen it or add more info anytime 😄

**Closed by matheuss** 2016-09-01 17:24 UTC
Labels: Can't Reproduce, Status: Awaiting Response

**Comment by THPubs** [comment] 2016-09-04 16:01
I'm also facing the same issue here. I'm on Linux (Ubuntu 16.04). Hyper process won't quit. If I try to close and open it again, there will be two processes running. :-)

**Comment by matheuss** [comment] 2016-09-04 20:17
Can you reproduce the same behavior in another terminal app, @THPubs?

**Comment by THPubs** [comment] 2016-09-05 00:32
@matheuss Nope. The system's gnome-terminal is working fine. Even checked with another electron app (Atom). It also behaves normally. Process killed after closing. :-)

**Comment by cmhrpr** [comment] 2018-10-12 11:32
I use Hyper on Windows, with the Linux Subsystem. I'm using zsh as my shell. When closing Hyper, the zsh processes are still running in the background

**Comment by fultonm** [comment] 2019-05-12 20:24
Yep. Process still running after closing Hyper. Git bash not doing this, because it prompts if I want to terminate the process or not.

**Comment by gabrielmbmb** [comment] 2019-05-14 16:54
> 
> 
> I use Hyper on Windows, with the Linux Subsystem. I'm using zsh as my shell. When closing Hyper, the zsh processes are still running in the background

That's happening to me also. I'm using WSL (Ubuntu) with ZSH and when I close the Hyper Window zsh process still alive.

**Comment by caiocutrim** [comment] 2019-12-24 15:13
That is happend to me too in 2019, I'm using ubuntu 19.10, and to kill the process I have to do it manually by searching the process id and kill it with `kill {process-id}` command.

**Comment by rohitkrishna094** [comment] 2020-01-04 18:24
Is there a solution to this? Or should we open a new issue since this still persists in 2020?

I am using fish. In hyper config, I have 
```shell: 'fish.exe',```

and if I close hyper without typing ```exit``` then, the fish process doesn't quit and  keeps running in the background. If I open another hyper instance or hyper again, then more fish shells are created thereby eating up memory.

I tried the same with bash.exe as well.
