### ISSUE TITLE
We could not find the 'npm' command. Make sure it's in $PATH

### ISSUE THREAD

**Issue by davidhq** [zeit/hyperterm#106] opened 2016-07-15 20:18 UTC
I get this notification from subject.

but 

```
$ which npm
/Users/david/n/bin/npm
```

works...

Not sure if it's related, when I add "hyperpower" plugin to `.hyperterm.js` and save it, nothing really happens and 

```
$ ls .hyperterm_plugins/
local        package.json
```

Any suggestions ?

Should "hyperpower" plugin install automatically after saving the file and is this not happening because of the problem about not finding 'npm' command supposedly?

**Comment by machi1990** [comment] 2016-07-15 20:22
To test the hyperpower plugin, you'll need to reload/full reload hyperterm.

**Comment by davidhq** [comment] 2016-07-15 20:26
After full reload I get: *“hyperpower” failed to load in the renderer
process. Check Developer Tools for details.*

**Comment by montogeek** [comment] 2016-07-15 20:27
Related: #89

**Comment by rauchg** [comment] 2016-07-15 20:40
This is the culprit:
https://github.com/zeit/hyperterm/blob/master/plugins.js#L191-L193

Basically it's not in the *OSX $PATH*. I welcome ideas on how to fix this. Electron launches the process in a non-user shell, so I'm not 100% sure how to fix this yet.

Any ideas @zcbenz @jlord?

**Comment by rauchg** [comment] 2016-07-15 20:41
Temporariy workaround: make `npm` accessible in `/usr/local/bin` or `/usr/bin`

**Comment by montogeek** [comment] 2016-07-15 20:42
@rauchg Yeah, from my log on #89 it runs a different `npm` and `node` versions

**Comment by marcbachmann** [comment] 2016-07-15 21:06
@rauchg check out https://github.com/maxogden/user-env

**Comment by montogeek** [comment] 2016-07-15 21:16
Uhmm, when running the app in develoipment node `npm start` the problem does not exist :/

**Comment by nilliams** [comment] 2016-07-15 23:32
Same issue. I have node and npm installed via nvm. Within the terminal (incl. hyperterm itself) I can `npm --version`, but hyperterm doesn't seem to be able to find it when editing plugins (adding 'hyperpower' doesn't work) :/.

**Comment by sandysaders** [comment] 2016-07-16 16:47
#145 related

**Comment by kennetpostigo** [comment] 2016-07-16 19:02
@montogeek @rauchg could using this help:
https://github.com/sindresorhus/run-node

**Comment by kennetpostigo** [comment] 2016-07-16 19:11
Not sure if this is something that can be used internally by hyperterm.

**Comment by sindresorhus** [comment] 2016-07-16 23:36
@kennetpostigo Yup, it's confirmed to work with `nvm`. It's based on a [**lot** of research](https://github.com/sindresorhus/alfred-npms/issues/1) into the problem.

Node.js version: https://github.com/sindresorhus/shell-env

**Comment by montogeek** [comment] 2016-07-16 23:38
It is already fixed on https://github.com/zeit/hyperterm/pull/172, I use `nvm`, tested it and it works :) at least on macOS

**Closed** 2016-07-17 17:28 UTC

**Comment by nilliams** [comment] 2016-07-17 18:10
Great work, Thanks!

However can I suggest not closing issues til the fix is actually released? I just re-downloaded the release and hit sadness.

**Comment by mkscrg** [comment] 2016-08-01 23:01
I use `nvm`, but I've removed the `default` alias because it makes new shells about 1s slower to load (compared to ~0s 😄). I added this to my `~/.bash_profile` to make HyperTerm work:

```bash
# HyperTerm.app runs `bash -ilc env` in an attempt to find npm
if [[ "$(ps -o command= $$)" =~ bash\ -ilc\ env &&
      "$(ps -o command= $PPID)" =~ HyperTerm\.app ]]; then
  nvm use stable
fi
```

**Comment by jitendravyas** [comment] 2017-02-07 03:31
i m also getting this error. Downloaded Hyperterm yesterday and added some plugins

**Comment by tatwater** [comment] 2017-08-15 15:29
I'm also getting this same error notification!
